export const ERR_MSG = {
  INVALID_USER: "Sorry you have entered a Invalid Username and/or Password.",
  UNAUTHORIZED: "Unauthorized",
  SOMETHING_WENT_WRONG: "Something went wrong please try again after sometime.",
  SESSION_TERMINATED: "Session terminated please login again",
  TOKEN_ERROR: "error occur in token verification",
  TOKEN_EXPIRED: "Token expired",
  INVALID_ENDPOINT: "Invalid api not found",
  UNDER_MAINTENANCE: "Application under maintenance",
  NO_SPECIAL_CHARACTER: "Special characters are not allowed.",
  MISSING_PARAMETERS: "Mandatory Parameters Missing!",
  INVALID_FORMAT: "Invalid format",
  MISSING_HEADERS: "Missing Headers",
  INVALID_CLIENT: "Invalid Client Credential",
  INVALID_CHANNEL_ID: "Invalid x-fapi-channel-id",
  BAD_REQUEST: "Bad Request",
  SESSION_EXPIRED: "Session Expired",
  ERROR: "Error !",
  STAGE_ERR: "Journey is in invliad State",
  APP_REF_ERR: "applicationReferenceId is not valid",
  PRINT_ERR: "data.applicationReferenceId",
  NOT_AVAILBLE: "Mobile Number is not valid",
};
